version: '3'

services:
  microservice-projet:
    image: esgimicroci/al2-projects
    ports:
      - "8080:8080"
    environment:
      DB_NAME: ${DB_NAME:-microserviceProjet}
      DB_USER: ${DB_USER:-root}
      DB_PASSWORD: ${DB_PASSWORD:-root}
      CONSUL_HOST: ${CONSUL_HOST}
      CONSUL_TOKEN: ${CONSUL_TOKEN}
      CONSUL_PORT: ${CONSUL_PORT}


  db:
    image: postgres
    environment:
      POSTGRES_USER: ${DB_USER:-root}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-root}
      POSTGRES_DB: ${DB_NAME:-microserviceProjet}
    volumes:
      - postgres:/data/postgres/project
    ports:
      - "5432:5432"
    restart: unless-stopped

volumes:
  postgres:


# Add your networks/volumes/services for your microservice
