version: '3'

services:
  db:
    image: postgres
    network_mode: bridge
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=postgres
      - POSTGRES_DB=microserviceProjet
    volumes:
      - postgres:/data/postgres/project
    ports:
      - "5432:5432"
    expose:
      - 5432
    restart: unless-stopped

  microservice-projet:
    image: esgimicroci/al2-projects
    ports:
      - "8080:8080"
    environment:
      DB_NAME: ${DB_NAME:-microserviceProjet}
      DB_USER: ${DB_USER:-root}
      DB_PASSWORD: ${DB_PASSWORD:-root}
      CONSUL_HOST: http://micro-ci.westus2.cloudapp.azure.com
      CONSUL_TOKEN: ab8bdda5-2a4a-1ebf-0383-95ccbebe63b4
      CONSUL_PORT: 40601
    volumes:
      - al2projects:/var/projects
    depends_on:
      - db
    links:
      - db

volumes:
  postgres:
  al2projects:
    external: true


# Add your networks/volumes/services for your microservice
