version: '3'

services:
  microservice-projet:
    image: micro-ci-al2/micro-ci-projects
    ports:
      - "8080:8080"
    environment:
      DB_NAME: ${DB_NAME:-microserviceProjet}
      DB_USER: ${DB_USER:-root}
      DB_PASSWORD: ${DB_PASSWORD:-root}
      CONSUL_HOST: micro-ci.westus2.cloudapp.azure.com
      CONSUL_TOKEN: ab8bdda5-2a4a-1ebf-0383-95ccbebe63b4
      CONSUL_PORT: 40601


  db:
    image: postgres
    environment:
      POSTGRES_USER: ${DB_USER:-root}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-root}
      POSTGRES_DB: ${DB_NAME:-microserviceProjet}
    volumes:
      - postgres:/data/postgres/project
    ports:
      - "5432:5432"
    restart: unless-stopped

volumes:
  postgres:


# Add your networks/volumes/services for your microservice
