version: '3'

services:
  db:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=microserviceProjet
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always

  microservice-projet:
    image: esgimicroci/al2-projects
    ports:
      - "8080:8080"
    environment:
      DB_NAME: ${DB_NAME:-microserviceProjet}
      DB_USER: ${DB_USER:-postgres}
      DB_PASSWORD: ${DB_PASSWORD:-admin}
      CONSUL_HOST: ${CONSUL_HOST:-http://micro-ci.westus2.cloudapp.azure.com}
      CONSUL_TOKEN: ab8bdda5-2a4a-1ebf-0383-95ccbebe63b4
      CONSUL_PORT: ${CONSUL_PORT:-40601}
    volumes:
      - al2projects:/var/projects
    depends_on:
      - db
    links:
      - db
    restart: always

volumes:
  postgres:
  al2projects:
    external: true


# Add your networks/volumes/services for your microservice
