package com.example.projects.models;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import lombok.Data;

@Data
@ApiModel(description = "All details about a Clone.")
public class Clone {


    @ApiModelProperty(notes = "Project name")
    private String name;

    @ApiModelProperty(notes = "The repository generated by the system")
    private String path;

    @ApiModelProperty(notes = "The source URL of the project")
    private String url;

    @ApiModelProperty(notes = "The project branch")
    private String branch;

}
