package com.example.projects.models;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import lombok.Data;
import lombok.Getter;
import lombok.Setter;

import javax.persistence.*;

@Getter
@Setter
@Data
@Entity
@Table(name = "projects")
@ApiModel(description = "All details about a Project.")
public class Project {
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    @ApiModelProperty(notes = "The database generated project ID")
    private Long _id;

    @ApiModelProperty(notes = "Project name")
    @Column(name = "name")
    private String name;

    @ApiModelProperty(notes = "The URL generated by the system")
    @Column(name = "url")
    private String url;

    @ApiModelProperty(notes = "The access right of the repository")
    @Column(name = "public")
    private Boolean _public;

    @ApiModelProperty(notes = "The default branch")
    @Column(name = "defaultBranch")
    private String defaultBranch;

    @ApiModelProperty(notes = "The ID of the owner")
    @Column(name = "owner")
    private String owner;
}
